chore: Converted AppInfo to TypeScript
equinor/hearing-test pull request #209
Opened 2023-05-24 08:10 UTC by ofredstie

Closes #205

2023-06-19 16:01 UTC, dansvend commented on components/AppInfo.tsx
>        renderSectionHeader={renderSectionHeader}
The type of the argument for `renderSectionHeader` in the `SectionList` component is different than your `Section` type.

2023-06-19 16:09 UTC, dansvend commented on components/AppInfo.tsx
> +      style={styles.container as StyleProp<ViewStyle>}
This prevents the TypeScript compiler to work as intended. You should be careful with casting types.

2023-06-23 10:29 UTC, ofredstie commented on components/AppInfo.tsx
> +interface Item {
:+1:

2023-06-29 14:30 UTC, ofredstie commented on components/AppInfo.tsx
>        renderSectionHeader={renderSectionHeader}
Fixed

2023-07-11 13:17 UTC, dansvend requested changes

2023-07-11 13:17 UTC, dansvend commented on components/AppInfo.tsx
> +export const AppInfo = ({ sections }: AppInfoProps) => {
Since you're now exporting it as a named export you can remove the default export at the bottom. This means that you need to change to named imports the places you use the `AppInfo` component.

2023-07-11 13:17 UTC, dansvend commented on components/AppInfo.tsx
> +type Section = {
This type should be exported and used in `AboutScreen` to define the type of `sections` to be `Section[]`.

2023-07-11 13:17 UTC, dansvend commented on components/AppInfo.tsx
> +  data: SimpleItem[];
`data` in `sections` in `AboutScreen` has a `key` prop. `key` should therefore be added to the type for the `data` prop.

2023-07-12 12:57 UTC, dansvend requested changes

2023-07-12 13:18 UTC, ofredstie commented on components/AppInfo.tsx
> +export const AppInfo = ({ sections }: AppInfoProps) => {
Damn, I was sure that I had removed that one, will fix is ASAP. 

Have already updated the imports of AppInfo component 👍

2023-08-16 07:25 UTC, nesadrian approved these changes

2023-08-16 07:28 UTC, dansvend approved these changes

2023-08-16 07:30 UTC, merged