refactor(SimpleInfoItem): Migrate to TypeScript
equinor/hearing-test pull request #210
Opened 2023-05-24 08:34 UTC by ofredstie

Migrate `SimpleInfoItem` from JavaScript to TypeScript.

Closes #204

2023-06-19 16:25 UTC, dansvend requested changes

2023-06-19 16:25 UTC, dansvend commented on components/common/atoms/SimpleInfoItem.tsx
> +import React, { ReactElement } from "react";
This line can be removed.

2023-06-19 16:25 UTC, dansvend commented on components/common/atoms/SimpleInfoItem.tsx
> +const SimpleInfoItem: React.FC<SimpleInfoItemProps> = ({
Let's remove `React.FC`.

2023-06-19 16:25 UTC, dansvend commented on components/common/atoms/SimpleInfoItem.tsx
> +}): ReactElement => (
Let's remove the return type.

2023-06-19 16:25 UTC, dansvend commented on components/common/atoms/SimpleInfoItem.tsx
> +  key: string;
I see the `Item` type require a `key` prop but it's not used anywhere.

2023-06-19 16:25 UTC, dansvend commented on components/common/atoms/SimpleInfoItem.tsx
> +interface Item {
This line can be removed.

2023-06-29 14:27 UTC, ofredstie commented
These changes are implemented as part of #209

2023-06-29 14:27 UTC, closed without merging