feat: Updated tone of voice
equinor/hearing-test pull request #214
Opened 2023-05-24 12:51 UTC by ofredstie

Translated English texts to Norwegian and updated general tone of voice

Closes #208

2023-08-18 11:42 UTC, dansvend commented on screens/FeedbackScreen.tsx
> +            setStatusMessage("Tusen takk for tilbakemeldingen");
Add exclamation mark at the end of the text.

2023-08-18 12:00 UTC, dansvend requested changes

2023-08-18 13:04 UTC, ofredstie commented on screens/FeedbackScreen.tsx
> +            setStatusMessage("Tusen takk for tilbakemeldingen");
I discussed this with Vetle when we did this change and we agreed that an exclamation mark is not needed here

2023-08-21 07:54 UTC, ofredstie commented on screens/FeedbackScreen.tsx
> +        informasjon:
We are literally listing the collected items below on line 164

2023-11-14 12:49 UTC, dansvend approved these changes

2023-11-15 06:41 UTC, nesadrian approved these changes

2023-11-15 07:04 UTC, merged