refactor(LogoutButton): Migrate to TypeScript
equinor/hearing-test pull request #226
Opened 2023-06-14 10:49 UTC by ofredstie

Converted from JavaScript to TypeScript and simplified logout button component

Closes #206

2023-07-12 07:35 UTC, dansvend requested changes

2023-07-12 07:35 UTC, dansvend commented on components/auth/LogoutButton.tsx
> +const LogoutButton = ({ onPress }: LogoutButtonProps) => (
I see you have removed a lot of logic related to the logout functionality. The point of making components is to improve reusability. By removing all of the auth logic you're basically making the `LogoutButton` just a copy of the `mad-expo-core` button with the text `Log out`. Please insert the redux and auth logic you removed.

2023-07-12 13:46 UTC, dansvend requested changes

2023-07-12 13:46 UTC, dansvend commented on components/auth/LogoutButton.tsx
> +const LogoutButton = ({ onPress }: LogoutButtonProps) => (
`LogoutButton` don't need to have any props. To use the navigation you can use the `useNavigation` hook.

2023-07-12 13:46 UTC, dansvend commented on components/auth/LogoutButton.tsx
> +});
Since `authStatus` is unused you can remove the whole `mapStateToProps`.

2023-07-12 13:46 UTC, dansvend commented on components/auth/LogoutButton.tsx
> +  signOut: () => dispatch(actions.loginSignOut()),
`signOut` is unused and can be removed.

2023-07-12 13:46 UTC, dansvend commented on components/auth/LogoutButton.tsx
> +  setConfig: (appConfig) => dispatch(actions.setConfig(appConfig)),
Since the component was rewritten to a functional component you should use the React Redux [useDispatch](https://react-redux.js.org/api/hooks#usedispatch) hook to `setConfig`.

2023-07-12 13:46 UTC, dansvend commented on components/auth/LogoutButton.tsx
> +export default connect(mapStateToProps, mapDispatchToProps)(LogoutButton);
You can remove this line and export the `LogoutButton` as a named export where the component is declared.

2023-07-12 13:46 UTC, dansvend commented on components/auth/LogoutButton.tsx
> +    }}
I would keep the `onPress` function as it was before to keep the reusability.

2023-07-13 09:42 UTC, ofredstie commented on components/auth/LogoutButton.tsx
> +  signOut: () => dispatch(actions.loginSignOut()),
You said previously that I had to undo my removal of this, but ok

2023-07-13 09:56 UTC, ofredstie commented on components/auth/LogoutButton.tsx
> +    }}
Not really sure what you want, you said previously that you wanted me to use useNavigation rather than passing onPress as a property

2023-07-13 10:34 UTC, ofredstie commented on components/auth/LogoutButton.tsx
> +export default connect(mapStateToProps, mapDispatchToProps)(LogoutButton);
It would be faster if you do this change, not sure how we are supposed to do named exports with redux connect()

2023-07-13 10:34 UTC, ofredstie commented on components/auth/LogoutButton.tsx
> +    }}
using the useNavigation hook

2023-07-19 08:37 UTC, closed without merging