fix: Sound playing after resetting test
equinor/hearing-test pull request #227
Opened 2023-06-15 10:35 UTC by ofredstie

Sound samples will now be played after the test is restarted.

Closes #218

2023-06-15 11:19 UTC, dansvend requested changes

2023-06-15 11:19 UTC, dansvend commented on screens/TestScreen.tsx
> +  restartTest() {
I see there are some code duplication in `abortTest` and `restartTest`. Would it be an idea to create another method called `stopTest` which can be reused in both `abortTest` and `restartTest`?

2023-06-15 11:19 UTC, dansvend commented on screens/TestScreen.tsx
> +                          this.props.navigation.navigate("TestRoute");
I don't know if we need this line since we're already in the `TestRoute`.

2023-06-15 11:19 UTC, dansvend commented on screens/TestScreen.tsx
> +const setAlert = (
There's already a function which we use to display alerts in alerts.ts. Would be nice if you could change that and use that instead. We want to separate out reusable utility functions and components so that they're easier to find and maintain.

2023-06-16 06:19 UTC, ofredstie commented on screens/TestScreen.tsx
> +const setAlert = (
I agree :+1:

2023-06-16 06:29 UTC, ofredstie commented on screens/TestScreen.tsx
> +                          this.props.navigation.navigate("TestRoute");
We didn't need it 😄

2023-06-16 08:52 UTC, nesadrian requested changes

2023-06-16 08:52 UTC, nesadrian commented on screens/TestScreen.tsx
> +                          //this.props.navigation.navigate("TestRoute");
I would delete this or add the reason why it's there in the code comment if it's important

2023-06-16 08:52 UTC, nesadrian commented on screens/TestScreen.tsx
> +  abortTest() {
The order of code execution order changes when the stopTest function call is at the top instead of the bottom in abortTest. If this is intended or insignificant then it's fine :)

2023-06-16 08:56 UTC, ofredstie commented on screens/TestScreen.tsx
> +                          //this.props.navigation.navigate("TestRoute");
My mistake, commented it out to test it, forgot to remove it. :+1:

2023-06-16 10:53 UTC, nesadrian approved these changes

2023-06-21 08:36 UTC, dansvend requested changes
Looks much better💪 I left some comments on possible improvements😊

2023-06-21 08:36 UTC, dansvend commented on utils/sound.ts
> +export const systemVolume: number = 0.5;
Also I think it's verbose to specify the type of this type of variable since the type is inferred by the TypeScript type inference system which takes responsibility away from us of writing the types.

2023-06-21 08:36 UTC, dansvend commented on utils/alerts.ts
> +  ]);
The `setAlert` function and the `onClose` is basically the same. You should only keep one of them, and a fitting name would be what you have, `setAlert`.

2023-06-21 08:36 UTC, dansvend commented on screens/TestScreen.tsx
> +import { setAlert } from "../utils/alerts";
Since you're not using `Alert` from `react-native` directly in this file anymore the import should be removed.

2023-06-21 08:36 UTC, dansvend commented on screens/TestScreen.tsx
> +    this.props.actionStartTest();
You might need to reset the `test`-reducer in redux to reset the user responses for example to start the new test without any user responses from the previous test run.

2023-06-21 08:36 UTC, dansvend commented on screens/TestScreen.tsx
> +    this.setState({ modalVisible: false });
I see the order of these two have been changed. Probably doesn't matter but I'd keep it the way it was to not potentially introduce new bugs.

2023-06-21 08:36 UTC, dansvend commented on utils/alerts.ts
> +  heading: string,
Could change this to `title` since that's the name `Alert.alert` uses to have consistency.

2023-06-21 08:36 UTC, dansvend commented on utils/alerts.ts
> +  description: string,
Could change this to `message` since that's the name `Alert.alert` uses to have consistency.

2023-06-21 08:36 UTC, dansvend commented on screens/TestScreen.tsx
> +                          this.props.navigation.navigate("TestRoute");
I see the navigation is still here. Is this needed? If so it could be added to the `restartTest` method.

2023-06-21 10:40 UTC, ofredstie commented on utils/alerts.ts
> +  heading: string,
Could not agree more.. :D

2023-06-21 10:40 UTC, ofredstie commented on utils/alerts.ts
> +  description: string,
I agree

2023-06-22 11:28 UTC, ofredstie commented on screens/TestScreen.tsx
> +    this.props.actionStartTest();
Tested with React Native Debugger and can verify that userResponses is reset after test is restarted

2023-08-18 08:54 UTC, dansvend requested changes

2023-08-18 08:54 UTC, dansvend commented on app.json
> +      "jsEngine": "jsc",
Does this still work when running Expo SDK 49?

2023-08-18 08:54 UTC, dansvend commented on screens/SoundCheckScreen.tsx
> +    // Load the sound file 'testBell.wav' from the app bundle
This comment can be removed.

2023-08-18 08:54 UTC, dansvend commented on utils/alerts.ts
> +export const setAlert = (
After thinking about this `confirmationDialog` is a more suitable name since "Ja" and "Nei" is hardcoded.

2023-08-18 08:54 UTC, dansvend commented on utils/alerts.ts
> +  onConfirm: CallableFunction
This should have a type similar to `onPress` on the `AlertButton` type.

2023-08-18 08:54 UTC, dansvend commented on utils/alerts.ts
> +      onPress: () => onConfirm(),
This can be changed to how it was.

2023-08-18 08:54 UTC, dansvend commented on screens/SoundCheckScreen.tsx
> +    SystemSetting.setVolume(SYSTEM_VOLUME, { showUI: false }); //Todo: Disabling this until we know how the calibration step should be done..
The `Todo` comment can be removed.

2023-08-18 08:54 UTC, dansvend commented on screens/TestScreen.tsx
> +import { SYSTEM_VOLUME } from "../constants/sounds";
Please remove import of `Alert` on line 5 since it's no longer in use.

2023-08-21 07:11 UTC, ofredstie commented on screens/TestScreen.tsx
> +                          this.props.navigation.navigate("TestRoute");
Navigation need to be there

2023-08-21 10:51 UTC, dansvend approved these changes

2023-08-21 11:06 UTC, nesadrian approved these changes

2023-08-22 08:08 UTC, merged