feat: Add mute button in test environment
equinor/hearing-test pull request #311
Opened 2023-11-28 11:36 UTC by dansvend

- Add mute button in `TestScreen` avialable in non production environments to improve the experience for internal testers.

Closes #299

2023-11-28 12:45 UTC, tormodAase requested changes

2023-11-28 12:45 UTC, tormodAase commented on screens/TestScreen.tsx
> +            />
I would put this in a separate component. isVolumeMuted can be a redux state. Then you can create a selector for volume that depends on isVolumeMuted

2023-11-28 12:54 UTC, tormodAase approved these changes

2023-11-28 13:08 UTC, dansvend commented on screens/TestScreen.tsx
> +            />
I'll do this in #310  🙌 Thanks for the feedback 🙏

2023-11-28 13:42 UTC, tormodAase approved these changes

2023-11-28 13:42 UTC, tormodAase commented on screens/TestScreen.tsx
> +    }
I would remove this part. if isVolumeMuted is true, you should always return 0. However, whether the user is able to mute should be decided elsewhere

2023-11-28 13:42 UTC, tormodAase commented on screens/TestScreen.tsx
> +            />
I would still separate this into a separate component. That way you can get rid of isProduction at the top of this file

2023-11-28 13:44 UTC, dansvend commented on screens/TestScreen.tsx
> +            />
Good point 🙏 I'll keep this in mind in #311 👌

2023-11-28 14:00 UTC, dansvend commented on screens/TestScreen.tsx
> +    }
Thanks for the feedback 🙏 I removed this part 👌

2023-11-28 14:01 UTC, dansvend commented on screens/TestScreen.tsx
> +            />
Good point 👌 I moved this into a separate component 📦

2023-11-28 14:02 UTC, tormodAase submitted a review, later dismissed

2023-11-29 11:04 UTC, tormodAase submitted a review, later dismissed

2023-11-30 10:23 UTC, tormodAase approved these changes

2023-11-30 15:01 UTC, merged