refactor: Use `LinearProgress` from `@equinor/mad-components`
equinor/hearing-test pull request #319
Opened 2023-12-04 17:17 UTC by dansvend

- Replace `ProgressBar` with `LinearProgress` from `@equinor/mad-components`.
- Update `ProgressAnimationBar` design to EDS.

Closes #301

2023-12-05 22:33 UTC, nesadrian approved these changes

2023-12-06 12:48 UTC, nesadrian approved these changes

2023-12-18 11:50 UTC, nesadrian commented on components/common/molecules/ProgressAnimationBar.tsx
> +      opacity: disabled ? 0 : 1,
Here you can use unary operators +!

2023-12-18 11:51 UTC, nesadrian commented on screens/TestScreen.tsx
> +                opacity: this.props.testIsRunning ? 1 : 0,
Here you can use unary operators +!

2023-12-18 11:59 UTC, nesadrian requested changes
See comments

2023-12-18 12:07 UTC, dansvend commented on components/common/molecules/ProgressAnimationBar.tsx
> +      opacity: disabled ? 0 : 1,
How would the implementation look like in this case? 🤔

2023-12-18 12:07 UTC, dansvend commented on screens/TestScreen.tsx
> +                opacity: this.props.testIsRunning ? 1 : 0,
How would the implementation look like in this case? 🤔

2023-12-18 12:14 UTC, nesadrian commented on components/common/molecules/ProgressAnimationBar.tsx
> +      opacity: disabled ? 0 : 1,
It would be +!disabled. So the "!" reverses the boolean and the "+" operator turns the boolean into a number. So if it is disabled it will turn the boolean from true to false first and false becomes the number 0 and vice versa

2023-12-18 13:33 UTC, dansvend commented on components/common/molecules/ProgressAnimationBar.tsx
> +      opacity: disabled ? 0 : 1,
Hmm.. Do you think that's more readable than the current implementation?

2023-12-18 15:01 UTC, nesadrian commented on components/common/molecules/ProgressAnimationBar.tsx
> +      opacity: disabled ? 0 : 1,
I think it looks cleaner, but it doesn't make much of a difference. I'll approve regardless

2023-12-18 15:01 UTC, nesadrian submitted a review, later dismissed

2023-12-20 14:49 UTC, tormodAase approved these changes

2023-12-21 07:22 UTC, merged