refactor: `TestScreen`
equinor/hearing-test pull request #340
Opened 2024-01-25 14:21 UTC by dansvend

- Refactor `TestScreen` from React class component to functional component and hooks.

Closes #310

2024-01-26 07:10 UTC, tormodAase requested changes

2024-01-26 07:59 UTC, dansvend commented on hooks/useHearingTestProgressBar.ts
> +export const useHearingTestProgressBar = () => {
Done in [b6d6057](https://github.com/equinor/hearing-test/pull/340/commits/b6d60575938c607db1c29cb02abdf0adc5715b83).

2024-01-26 08:04 UTC, dansvend commented on hooks/useHearingTestSoundFiles.ts
> +  const soundsRef = useRef<{ [key: string]: Sound }>({});
Done in [ae07a20](https://github.com/equinor/hearing-test/pull/340/commits/ae07a208e8919216a2c4271eb6d4b865dbf385f5).

2024-01-26 08:15 UTC, dansvend commented on hooks/useHearingTestSoundFiles.ts
> +  const isDemoMode = getIsDemoModeEnabled();
Done in [1ccf44d](https://github.com/equinor/hearing-test/pull/340/commits/1ccf44dcf22dc953fcb50a0c23f5060449c3c27e).

2024-01-26 08:26 UTC, dansvend commented on hooks/useHearingTestProgressBar.ts
> +  }, [isProgressBarInitialized, test]);
Done in [ebc90f9](https://github.com/equinor/hearing-test/pull/340/commits/ebc90f9bb25fd9b36eba04728b83e682a17cbbc3).

2024-01-26 11:30 UTC, dansvend commented on contexts/VolumeContext.tsx
> +          console.error("Error setting initial system volume", err)
Done in [b7447c2](https://github.com/equinor/hearing-test/pull/340/commits/b7447c20908ee06d75ae723796917b79364fe547). We'll add toasts for rejected promises when we get a toast system implemented in [@equinor/mad-core](https://www.npmjs.com/package/@equinor/mad-core).

2024-01-26 12:43 UTC, dansvend commented on hooks/useHearingTestSoundFiles.ts
> +  const soundsRef = useRef<{ [key: string]: Sound }>({});
Done in [e25046d](https://github.com/equinor/hearing-test/pull/340/commits/e25046de60e26aa6b97f139766e96b33abf6a181).

2024-01-26 13:06 UTC, tormodAase approved these changes

2024-01-31 10:37 UTC, tormodAase approved these changes

2024-01-31 11:34 UTC, merged